import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy | Maelstrom Frames',
  description: 'Privacy Policy for Maelstrom Frames - Professional Photography & Videography Services in Perinthalmanna, Kerala.',
  alternates: {
    canonical: '/privacy-policy',
  },
}

export default function PrivacyPolicy() {
  return (
    <div className="pt-28 md:pt-36 pb-16 md:pb-24 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Header without Hero */}
          <div className="border-b border-gray-200 pb-6 mb-8">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-serif font-bold text-gray-900 mb-4 leading-tight">
              Privacy Policy
            </h1>
            <p className="text-gray-500 text-sm md:text-base font-medium">
              Last updated: June 01, 2026
            </p>
          </div>

          <div className="text-gray-700 space-y-6 text-sm md:text-base leading-relaxed">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p>
                We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Interpretation and Definitions
              </h2>
              
              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Interpretation
              </h3>
              <p>
                The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Definitions
              </h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 mb-4 space-y-3 text-gray-600">
                <li>
                  <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                </li>
                <li>
                  <p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                </li>
                <li>
                  <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Maelstrom Frames Pvt. Ltd, Door No 33/157, CP Tower (2nd Floor), Ootty Road, Perinthalmanna, Kerala 679322.</p>
                </li>
                <li>
                  <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                </li>
                <li>
                  <p><strong>Country</strong> refers to: Kerala, India</p>
                </li>
                <li>
                  <p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                </li>
                <li>
                  <p><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</p>
                  <p className="mt-1">We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
                </li>
                <li>
                  <p><strong>Service</strong> refers to the Website.</p>
                </li>
                <li>
                  <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                </li>
                <li>
                  <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                </li>
                <li>
                  <p><strong>Website</strong> refers to Maelstrom Frames, accessible from <Link href="/" className="text-warm-600 hover:text-warm-700 underline transition-colors">https://www.maelstromframes.com/</Link>.</p>
                </li>
                <li>
                  <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                </li>
              </ul>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Collecting and Using Your Personal Data
              </h2>
              
              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Types of Data Collected
              </h3>
              
              <h4 className="text-lg font-semibold text-gray-800 mt-4 mb-2">
                Personal Data
              </h4>
              <p>
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This information is collected when You voluntarily submit it through contact forms, inquiry forms, booking request forms, or any other form available on the Website. Personally identifiable information collected may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1.5 text-gray-600">
                <li>Full name (first name and last name)</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Event or project details You choose to share in form submissions</li>
              </ul>
              <p>
                We do not collect payment information directly. Any payments processed through the Service are handled by third-party payment providers subject to their own privacy policies.
              </p>

              <h4 className="text-lg font-semibold text-gray-800 mt-4 mb-2">
                Usage Data
              </h4>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>
                Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p>
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              <p>
                We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
              </p>

              <h4 className="text-lg font-semibold text-gray-800 mt-4 mb-2">
                Tracking Technologies and Cookies
              </h4>
              <p>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-3 text-gray-600">
                <li>
                  <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
                </li>
                <li>
                  <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                </li>
              </ul>
              <p>
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
              </p>
              <p>
                Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.
              </p>
              <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
              <ul className="list-disc pl-6 mb-4 space-y-4 text-gray-600">
                <li>
                  <p><strong>Necessary / Essential Cookies</strong></p>
                  <p className="text-sm text-gray-500">Type: Session Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                </li>
                <li>
                  <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                  <p className="text-sm text-gray-500">Type: Persistent Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                </li>
                <li>
                  <p><strong>Functionality Cookies</strong></p>
                  <p className="text-sm text-gray-500">Type: Persistent Cookies | Administered by: Us</p>
                  <p className="mt-1">Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                </li>
                <li>
                  <p><strong>Analytics Cookies</strong></p>
                  <p className="text-sm text-gray-500">Type: Persistent Cookies | Administered by: Third Parties (e.g., Google Analytics)</p>
                  <p className="mt-1">Purpose: These Cookies are used to collect information about how visitors interact with Our Website, including pages visited, time spent, traffic sources, and device/browser information. We use this data to understand and improve website performance and user experience. Google Analytics may set cookies such as <em>_ga</em>, <em>_gid</em>, and <em>_gat</em> on Your device. You can opt out of Google Analytics tracking by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-warm-600 hover:text-warm-700 underline">Google Analytics Opt-out Browser Add-on</a>.</p>
                </li>
                <li>
                  <p><strong>Advertising and Remarketing Cookies</strong></p>
                  <p className="text-sm text-gray-500">Type: Persistent Cookies | Administered by: Third Parties (e.g., Meta/Facebook, Google)</p>
                  <p className="mt-1">Purpose: These Cookies are used to deliver advertisements relevant to You and Your interests, and to track the effectiveness of Our advertising campaigns. They may also be used to limit the number of times You see an advertisement and to measure and report on the performance of ad campaigns. These Cookies are set by Our advertising partners (such as Meta Platforms, Inc.) and may track Your activity across other websites.</p>
                </li>
              </ul>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Use of Your Personal Data
              </h3>
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 mb-4 space-y-3 text-gray-600">
                <li>
                  <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
                </li>
                <li>
                  <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                </li>
                <li>
                  <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                </li>
                <li>
                  <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                </li>
                <li>
                  <strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.
                </li>
                <li>
                  <strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
                </li>
                <li>
                  <strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                </li>
                <li>
                  <strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                </li>
                <li>
                  <strong>For advertising and remarketing:</strong> We may use Your Personal Data, Usage Data, and information collected via cookies and tracking technologies to serve targeted advertisements to You on third-party platforms such as Meta (Facebook and Instagram) and Google. This includes creating custom audiences and lookalike audiences on these platforms based on information You have provided to Us or Your interactions with Our Service.
                </li>
                <li>
                  <strong>To analyze Service performance:</strong> We use tools such as Google Analytics to understand how users interact with Our Website, monitor traffic trends, and improve overall user experience.
                </li>
              </ul>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Third-Party Analytics and Advertising Services
              </h3>
              <p>We use the following third-party services to help Us understand website usage and run advertising campaigns. Each of these services may collect data independently in accordance with their own privacy policies:</p>
              <ul className="list-disc pl-6 mb-4 space-y-3 text-gray-600">
                <li>
                  <strong>Google Analytics</strong> (Google LLC) — Used for website analytics. Data is processed in accordance with the <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-warm-600 hover:text-warm-700 underline">Google Privacy Policy</a>.
                </li>
                <li>
                  <strong>Meta Pixel / Meta Ads</strong> (Meta Platforms, Inc.) — We use the Meta Pixel on Our Website to measure the effectiveness of Our advertising campaigns on Facebook and Instagram, to build custom audiences for retargeting, and to serve relevant ads. Data is processed in accordance with the <a href="https://www.facebook.com/privacy/policy/" target="_blank" rel="noopener noreferrer" className="text-warm-600 hover:text-warm-700 underline">Meta Privacy Policy</a>.
                </li>
              </ul>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Retention of Your Personal Data
              </h3>
              <p>
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p>
                Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed. We apply different retention periods to different categories of Personal Data:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-3 text-gray-600">
                <li>
                  <strong>Account Information:</strong> User Accounts are retained for the duration of your account relationship plus up to 24 months after account closure.
                </li>
                <li>
                  <strong>Customer Support Data:</strong> Correspondence is kept up to 24 months from ticket closure; chat transcripts are kept up to 24 months for quality assurance.
                </li>
                <li>
                  <strong>Usage Data:</strong> Website analytics and server logs are retained for up to 24 months from the date of collection.
                </li>
              </ul>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Transfer of Your Personal Data
              </h3>
              <p>
                Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ.
              </p>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Delete Your Personal Data
              </h3>
              <p>
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
              </p>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Disclosure of Your Personal Data
              </h3>
              <h4 className="text-lg font-semibold text-gray-800 mt-4 mb-2">Business Transactions</h4>
              <p>
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>
              
              <h4 className="text-lg font-semibold text-gray-800 mt-4 mb-2">Law enforcement</h4>
              <p>
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>

              <h3 className="text-xl font-serif font-semibold text-gray-800 mt-6 mb-3">
                Security of Your Personal Data
              </h3>
              <p>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Children&apos;s Privacy
              </h2>
              <p>
                Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
              </p>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Links to Other Websites
              </h2>
              <p>
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
              </p>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Changes to this Privacy Policy
              </h2>
              <p>
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
              </p>

              <h2 className="text-2xl md:text-3xl font-serif font-bold text-gray-900 mt-8 mb-4 border-b border-gray-100 pb-2">
                Contact Us
              </h2>
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-6 mb-4 space-y-2 text-gray-600">
                <li>
                  By email: <a href="mailto:connect@maelstromframes.com" className="text-warm-600 hover:text-warm-700 underline">connect@maelstromframes.com</a>
                </li>
                <li>
                  By visiting this page on our website: <Link href="/contact" className="text-warm-600 hover:text-warm-700 underline">https://www.maelstromframes.com/contact</Link>
                </li>
                <li>
                  By phone: +91 7907742698
                </li>
                <li>
                  By mail: Maelstrom Frames Pvt. Ltd, Door No 33/157, CP Tower (2nd Floor), Ootty Road, Perinthalmanna, Kerala 679322
                </li>
              </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
